#ifndef ADVENTURE_H
#define ADVENTURE_H
#include <common.h>

#define WARPPAD_TRACKS 22 //not bosses
#define MAX_TRACKS 27 //max custom track number in this mod
#define NUM_CHARACTERS 16
#define ADV_PRIZE 6 //adventure prizes are levelID + 6


extern unsigned char load_track;
extern unsigned char current_track;
extern unsigned char prev_levID;
extern bool show_stars;

#define battle_levels_ (current_track == N_SANITY_4 || current_track == LOST_RUINS_4 || current_track == GLACIER_4 || current_track == CITADEL_4)

extern unsigned char laps;
extern const char* track_names[MAX_TRACKS];

enum TRACK_FILE_IN_BIGFILE
{
	//RELIC RACE/TIME TRIAL IN BIGFILE
	COVE_VRM = 30,
	COVE_LEV = 31,
	TUBES_VRM = 54,
	TUBES_LEV = 55,
	MCAVES_VRM = 78,
	MCAVES_LEV = 79,
	SEWER_VRM = 70,
	SEWER_LEV = 71,
	SKROCK_VRM = 168,
	SKROCK_LEV = 169,
	TEMPLE_VRM = 38,
	TEMPLE_LEV = 39,
	CPARK_VRM = 118,
	CPARK_LEV = 119,
	PPYRAMID_VRM = 46,
	PPYRAMID_LEV = 47,
	DCANYON_VRM = 6,
	DCANYON_LEV = 7,
	RAMPAGER_VRM = 152,
	RAMPAGER_LEV = 153,
	BBLUFF_VRM = 22,
	BBLUFF_LEV = 23,
	DMINES_VRM = 14,
	DMINES_LEV = 15,
	POLARP_VRM = 102,
	POLARP_LEV = 103,
	TINYA_VRM = 126,
	TINYA_LEV = 127,
	ROCKYR_VRM = 184,
	ROCKYR_LEV = 185,
	NGLABS_VRM = 94,
	NGLABS_LEV = 95,
	CTCASTLE_VRM = 86,
	CTCASTLE_LEV = 87,
	HTSKYWAY_VRM = 62,
	HTSKYWAY_LEV = 63,
	OXSTATION_VRM = 110,
	OXSTATION_LEV = 111,
	NITRO_COURT_VRM = 144,
	NITRO_COURT_LEV = 145,
	SLIDEC_VRM = 134,
	SLIDEC_LEV = 135,
	TURBOT_VRM = 142,
	TURBOT_LEV = 143,


	//1P ARCADE FILES
	BOSS1_VRM = 48,
	BOSS1_LEV = 49,
	BOSS2_VRM = 40,
	BOSS2_LEV = 41,
	BOSS3_VRM = 8,
	BOSS3_LEV = 9,
	BOSS4_VRM = 56,
	BOSS4_LEV = 57,
	BOSS5_VRM = 104,
	BOSS5_LEV = 105


};

enum TRACK_NAME_IN_LNG
{
	//THE NAME OF EVERY TRACK IN ADVENTURE MODE
	DINGO_CANYON_NAME = 110,
	DRAGON_MINES_NAME,
	BLIZZARD_BLUFF_NAME,
	CRASH_COVE_NAME,
	TIGER_TEMPLE_NAME,
	PAPU_PYRAMID_NAME,
	ROO_TUBES_NAME,
	HOT_AIR_SKYWAY_NAME,
	SEWER_SPEEDWAY_NAME,
	MYSTERY_CAVES_NAME,
	CORTEX_CASTLE_NAME,
	N_GIN_LABS_NAME,
	POLAR_PASS_NAME,
	OXIDE_STATION_NAME,
	COCO_PARK_NAME,
	TINY_ARENA_NAME,
	SLIDE_COLISEUM_NAME,
	TURBO_TRACK_NAME,
	SKULL_ROCK_NAME = 101,
	NITRO_COURT_NAME = 98,
	RAMPAGE_RUINS_NAME,
	ROCKY_ROAD_NAME = 103,

	//BOSS GARAGE NAME
	BOSS1_GARAGE_NAME = 355,
	BOSS2_GARAGE_NAME,
	BOSS3_GARAGE_NAME,
	BOSS4_GARAGE_NAME,
	BOSS5_GARAGE_NAME,

	//BOSS NAME
	BOSS4_NAME = 52,
	BOSS2_NAME,
	BOSS1_NAME,
	BOSS3_NAME,
	BOSS5_NAME = 57,


};

enum ADVENTURE_TRACKS
{

	N_SANITY_1,
	N_SANITY_2,
	N_SANITY_3,
	N_SANITY_4,
	N_SANITY_5,
	GEMSTONE_1,
	GEMSTONE_2,
	LOST_RUINS_1,
	LOST_RUINS_2,
	LOST_RUINS_3,
	LOST_RUINS_4,
	LOST_RUINS_5,
	GLACIER_1,
	GLACIER_2,
	GLACIER_3,
	GLACIER_4,
	GLACIER_5,
	CITADEL_1,
	CITADEL_2,
	CITADEL_3,
	CITADEL_4,
	CITADEL_5,
	N_SANITY_BOSS,
	LOST_RUINS_BOSS,
	GLACIER_BOSS,
	CITADEL_BOSS,
	FINAL_BOSS

};

enum CLASSES
{
	INTERMEDIATE,
	SKILLED,
	ADVANCED,
	BEGINNER


};



#endif