#ifndef UTILS_H
#define UTILS_H

#include <common.h>

//TODO: Commented need to replace octr->special with USE_
// extern bool USE_RETRO_FUELED;
extern bool USE_SHORTCUTLESS;
extern bool USE_N_VERTED;
// extern bool USE_MIRROR;
// extern bool USE_MOON_GRAVITY;
extern bool USE_NIGHT_FILTER;
// extern bool USE_BOUNDLESS;
// extern bool USE_WALL_RIDE;
// extern bool USE_SPEEDWAY_PHYSICS;

extern char* decalText;
extern struct GameTracker *gGT;

//TODO: octr->special will be deprecated as we need to be able to combine gamemodes and not just 1 enabled
// Replace with bitmask like quadflags
enum GAME_MODES {
	NORMAL = 0,
	MIRROR = 1,
	ICY_TRACKS = 2,
	ITEMLESS = 3,
	MOON_MODE = 4,
	RETRO_FUELED = 5,
	VOID_WORLD = 6,
	BOSS_RACE = 7,
	DEMO_CAMERA = 8,
	N_VERTED = 9,
	SHORTCUTLESS = 10,
	NIGHT = 11,
	DARKNESS = 12,
};

enum WEATHER_TYPE {
    WEATHER_NONE,
    WEATHER_RAIN,
    WEATHER_SNOW,
};

enum FIRE_LEVEL {
	SACRED = 0x100,
	USF = 0x800
};

enum ITEMS {
	ITEM_TURBO_BOOST = 0,
	ITEM_BOWLING_BOMB,
	ITEM_TRACKING_MISSILE,
	ITEM_EXPLOSIVE_CRATE,
	ITEM_N_BRIO_BEAKER,
	ITEM_SPRING,
	ITEM_POWER_SHIELD,
	ITEM_MASK,
	ITEM_N_TROPY_CLOCK,
	ITEM_WARP_ORB,
	ITEM_BOWLING_BOMB_X3,
	ITEM_TRACKING_MISSILE_X3,
	ITEM_INVISIBILITY,
	ITEM_SUPER_ENGINE
};

enum QUADBLOCKFLAGS {

	Q_NONE = 0,
	Q_INVISIBLE = (1 << 0),
	Q_GRAVITY = (1 << 1),
	Q_REFLECTION = (1 << 2),
	Q_KICKERS = (1 << 3),
	Q_OOF_BOUNDS = (1 << 4),
	Q_NV_USED = (1 << 5),
	Q_TRIGGER_SCRIPT = (1 << 6),
	Q_REVERB = (1 << 7),
	Q_KICKERS2 = (1 << 8),
	Q_MASK_GRAB = (1 << 9),
	Q_TEMPLE_DOOR = (1 << 10),
	Q_COLLISION_TRIGGER = (1 << 11),
	Q_GROUND = (1 << 12),
	Q_WALL = (1 << 13),
	Q_NO_COLL = (1 << 14),
	Q_INV_TRIGGERS = (1 << 15),
	Q_ALL = -1

};

enum SOUNDFX
{
	fx_menu_selection_change,
	fx_menu_confirm,
	fx_button_back,
	fx_letter_del,
	fx_some_ding_sound,
	fx_menu_locked,
	fx_kart_hit_wall,
	fx_kart_land,
	fx_kart_hop,
	fx_weapon_spring,
	fx_kart_collide_strong,
	fx_kart_collide_weak,
	fx_barrel_land,
	fx_kart_turbo_mini,
	fx_kart_turbo_full,
	fx_weapon_bomb_hit2,
	fx_kart_slowdown,
	fx_kart_skid,
	fx_kart_roll_offroad,
	fx_kart_roll_ice,
	fx_kart_curb,
	fx_kart_roll_wood,
	fx_kart_roll_ice2,
	fx_kart_roll_snow,
	fx_kart_roll_offroad2,
	fx_ambient_water,
	fx_kart_roll_metal,
	fx_roll_water,
	fx_en_kart_crash_yes,
	fx_en_kart_cortex_yes,
	fx_en_kart_tiny_yes,
	fx_en_kart_coco_yes,
	fx_en_kart_ngin_yes,
	fx_en_kart_dingo_yes,
	fx_en_kart_polar_yes,
	fx_en_kart_pura_yes,
	fx_en_kart_pinstripe_yes,
	fx_en_kart_papu_yes,
	fx_en_kart_roo_yes,
	fx_en_kart_joe_yes,
	fx_en_kart_ntropy_yes,
	fx_en_kart_pen_yes,
	fx_en_kart_fake_yes,
	fx_en_kart_oxide_yes,
	fx_en_kart_crash_hit,
	fx_en_kart_cortex_hit,
	fx_en_kart_tiny_hit,
	fx_en_kart_coco_hit,
	fx_en_kart_ngin_hit,
	fx_en_kart_dingo_hit,
	fx_en_kart_polar_hit,
	fx_en_kart_pura_hit,
	fx_en_kart_pinstripe_hit,
	fx_en_kart_papu_hit,
	fx_en_kart_roo_hit,
	fx_en_kart_joe_hit,
	fx_en_kart_ntropy_hit,
	fx_en_kart_pen_hit,
	fx_en_kart_fake_hit,
	fx_en_kart_oxide_hit,
	fx_crate_smash,
	fx_weapon_tnt_explosion,
	fx_weapon_tnt_buzz,
	fx_weapon_beaker_hit,
	fx_time_crate_freeze,
	fx_juiced_up,
	fx_pickup_wumpa_crate,
	fx_pickup_wumpa_single,
	fx_weapon_clock_deploy,
	fx_semaphor,
	fx_semaphor2,
	fx_weapon_bomb_fire,
	fx_weapon_bomb_loop,
	fx_weapon_bomb_hit,
	fx_weapon_rocket_fire,
	fx_weapon_rocket_loop,
	fx_weapon_rocket_hit,
	fx_weapon_orb_deploy,
	fx_weapon_orb_loop,
	fx_weapon_orb_gone,
	fx_weapon_tnt_pickup,
	fx_bounce,
	fx_weapon_deploy,
	fx_weapon_aku_aku,
	fx_weapon_uka_uka,
	fx_char_pitfall,
	fx_weapon_tracking,
	fx_weapon_shield_on,
	fx_weapon_shield_off,
	fx_weapon_shield_loop,
	fx_squash_in,
	fx_squash_out,
	fx_water_splash,
	fx_weapon_roulette_loop,
	fx_weapon_roulette_done,
	fx_weapon_rocket_hit2,
	fx_weapon_engine,
	fx_weapon_invisible_in,
	fx_weapon_invisible_out,
	fx_relic_discount,
	fx_letter_pickup,
	fx_menu_switch,
	fx_lap_cross,
	fx_prize_awarded,
	fx_temple_flames,
	fx_fire_bum,
	fx_weapon_spring2,
	fx_plant_chew,
	fx_plant_hit,
	fx_plant_hit2,
	fx_plant_chew2,
	fx_plant_spit,
	fx_armadillo_roll,
	fx_amadillo_hit,
	fx_minecart_roll,
	fx_boulder_roll,
	fx_barrel_roll,
	fx_temple_door,
	fx_skyway_engine,
	fx_seal_tum_around,
	fx_seal_hit,
	fx_spider_up,
	fx_spider_down,
	fx_spider_hit,
	fx_spider_hit_loop,
	fx_turtle_splash,
	fx_turtle_bounce,
	fx_ambient_station,
	fx_squash_out2,
	fx_fireball_spawn,
	fx_ambient_water2,
	fx_ambient_water3,
	fx_ambient_mines,
	fx_seagull,
	fx_ambient_drip,
	fx_ambient_tubes,
	fx_ambient_speedway,
	fx_ambient_wind,
	fx_ambient_skyway,
	fx_pipe_hiss,
	fx_roll_water2,
	fx_roll_water3,
	fx_ambient_lab,
	fx_glide_or_wind,
	fx_ambient_lab2,
	fx_neon_buzz,
	fx_stadium_audience,
	fx_hub_door_unlock,
	fx_hub_door_open,
	fx_boss_door,
	fx_oxide_door,
	fx_warppad_warp,
	fx_warppad_loop,
	fx_savescreen_scanline,
	fx_prize_pickup,
	fx_menu_intro_c,
	fx_menu_intro_t,
	fx_menu_intro_r,
	fx_menu_intro_ctr,
	fx_menu_intro_ring,
	fx_menu_intro_transition,
	fx_menu_intro_throwtrophy,
	fx_menu_intro_catchtrophy,
	fx_podium_crash_step,
	fx_podium_crash_swing,
	fx_podium_crash_sleep01,
	fx_podium_crash_sleep02,
	fx_podium_cortex_laugh,
	fx_podium_cortex_sad,
	fx_podium_crash_step2,
	fx_podium_tiny_roar1,
	fx_podium_tiny_roar2,
	fx_podium_coco_typing01,
	fx_podium_coco_typing02,
	fx_podium_ngin_idle,
	fx_podium_ngin_steam,
	fx_podium_dingo_step,
	fx_podium_dingo_laser,
	fx_en_kart_polar_yes2,
	fx_podium_polar_snore,
	fx_en_kart_pura_yes2,
	fx_podium_pura_lick,
	fx_podium_stripe_gunfire,
	fx_podium_stripe_gunclick,
	fx_podium_stripe_gunshake,
	fx_podium_papu_belly,
	fx_podium_papu_step,
	fx_podium_roo_bounce,
	fx_podium_roo_step,
	fx_podium_joe_sad,
	fx_podium_joe_woosh01,
	fx_podium_joe_woosh02,
	fx_podium_tropy_sad,
	fx_podium_tropy_spring,
	fx_podium_penta_step,
	fx_podium_penta_spin,
	fx_podium_fakecrash_swing,
	fx_podium_fakecrash_step,
	fx_podium_oxide_step,
	fx_cutscenes_birds,
	fx_cutscenes_forest,
	fx_cutscenes_racing,
	fx_cutscene_tinytiger1,
	fx_cutscene_ship_terminal1,
	fx_cutscene_ship_terminal2,
	fx_cutscene_ship_terminal3,
	fx_cutscene_ship_terminal4,
	fx_cutscenes_cocotyping1,
	fx_cutscenes_cocotyping2,
	fx_cutscene_cortex_laugh,
	fx_cutscenes_machineactive,
	fx_cutscene_tinytiger2,
	fx_cutscene_dingodile,
	fx_cutscene_ambience_blizzard,
	fx_cutscene_cortex_power,
	fx_cutscene_cameramove,
	fx_cutscene_cameramove2,
	fx_chara_crash_yoyo1,
	fx_chara_crash_yoyo2,
	fx_chara_crash_yoyo3,
	fx_neon_buzz2,
	fx_whoosh_high,
	fx_chara_cortex_buttons,
	fx_chara_cortex_machine,
	fx_chara_tiny_weights1,
	fx_chara_tiny_weights2,
	fx_chara_tiny_weights03_unused,
	fx_chara_tiny_grunt1,
	fx_chara_tiny_grunt2,
	fx_chara_coco_buttons1,
	fx_chara_coco_buttons2,
	fx_glide_or_wind2,
	fx_chara_ngin_hammer,
	fx_chara_ngin_hammer2,
	fx_chara_dingo_refill,
	fx_chara_dingo_refill2,
	fx_podium_joe_woosh01_2,
	fx_podium_joe_woosh02_2,
	fx_chara_dingo_fumance,
	fx_en_kart_polar_yes3,
	fx_ambient_wind2,
	fx_chara_pura_pur,
	fx_chara_pura_steps,
	fx_chara_pura_birds1,
	fx_chara_pura_birds2,
	fx_chara_pura_birds3,
	fx_mask_spawn_instrumental,
	fx_box_intro_smash1,
	fx_box_intro_smash2,
	fx_box_intro_smash3,
	fx_box_intro_open,
	fx_box_intro_teaser,
	fx_pew_zap01,
	fx_box_intro_aku,
	fx_whoosh_long_doppler,
	fx_box_intro_karts,
	fx_mask_spawn,
	fx_mask_gone
};

#endif